drop table if exists lecture cascade;

drop table if exists lecture_application cascade;

create table if not exists lecture (
     capacity integer not null,
     end_time timestamp(6) not null,
     id bigint generated by default as identity,
     start_time timestamp(6) not null,
     description varchar(255),
     speaker varchar(255) not null,
     title varchar(255) not null,
     primary key (id)
);

create table lecture_application (
     applied_at timestamp(6) not null,
     id bigint generated by default as identity,
     lecture_id bigint not null,
     member_id varchar(255),
     primary key (id),
     unique (lecture_id, member_id)
);

alter table if exists lecture_application
add constraint FKpqtlw6roaoj4u08m39cj4nwq9
foreign key (lecture_id)
references lecture